[package]
name = "rust_mp3_id3_chapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "1.2.0"
egui = "0.18.1"
eframe = "0.18.0"